# ===================================
#  List Behavior Config
# ===================================

title: Matches
list: ~/plugins/stu177/leagueTracker/models/match/columns.yaml
modelClass: Stu177\LeagueTracker\Models\Match
recordUrl: stu177/leagueTracker/match/update/:id
noRecordsMessage: No matches to display.
showCheckboxes: true
toolbar:
    buttons: list_toolbar
